# Generated by Django 2.2.3 on 2019-07-25 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StartYear', models.IntegerField()),
                ('EndYear', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Post', models.CharField(max_length=1000, null=True)),
                ('OfficiallyReported', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('unsure', 'Unsure')], default=None, max_length=6)),
                ('Year', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='DSAProject.SchoolYear')),
            ],
        ),
    ]
